# Snowflake Configuration Template
# Copy this file to snowflake_config.yaml and update with your credentials

snowflake:
  account: "your_account.region"  # e.g., "UYHVKHT-NU85773"
  user: "your_username"           # e.g., "DYTS"
  password: "your_password"       # Your Snowflake password
  warehouse: "COMPUTE_WH"
  database: "WAMEX_EXPLORATION"
  schema: "SNOWFLAKE_WAMEX"
  role: "ACCOUNTADMIN"

# Table Configuration
tables:
  wamex_geo:
    name: "WAMEX_GEO"
    description: "Geological exploration reports with geospatial data"
    columns:
      - name: "ANUMBER"
        type: "NUMBER"
        description: "Report number"
      - name: "TITLE"
        type: "STRING"
        description: "Report title"
      - name: "REPORT_YEA"
        type: "NUMBER"
        description: "Report year"
      - name: "AUTHOR_NAM"
        type: "STRING"
        description: "Author name"
      - name: "AUTHOR_COM"
        type: "STRING"
        description: "Author company"
      - name: "REPORT_TYP"
        type: "STRING"
        description: "Report type"
      - name: "DATE_FROM"
        type: "DATE"
        description: "Start date"
      - name: "DATE_TO"
        type: "DATE"
        description: "End date"
      - name: "PROJECT"
        type: "STRING"
        description: "Project name"
      - name: "OPERATOR"
        type: "STRING"
        description: "Operator"
      - name: "ABSTRACT"
        type: "STRING"
        description: "Report abstract"
      - name: "KEYWORDS"
        type: "STRING"
        description: "Keywords"
      - name: "TARGET_COM"
        type: "STRING"
        description: "Target commodity"
      - name: "DATE_RELEA"
        type: "DATE"
        description: "Release date"
      - name: "ITEM_NO"
        type: "NUMBER"
        description: "Item number"
      - name: "DPXE_ABS"
        type: "STRING"
        description: "DPXE abstract URL"
      - name: "DPXE_REP"
        type: "STRING"
        description: "DPXE report URL"
      - name: "EXTRACT_DA"
        type: "DATE"
        description: "Extraction date"
      - name: "DIGITAL_FI"
        type: "NUMBER"
        description: "Digital file flag"
      - name: "IS_SHAPED"
        type: "NUMBER"
        description: "Shapefile flag"
      - name: "geometry"
        type: "GEOGRAPHY"
        description: "Geospatial geometry"

# Data Loading Configuration
data_loading:
  csv_file: "Exploration_Reports_1000.csv"
  stage_name: "@%wamex_geo"
  file_format: "CSV"
  field_delimiter: ","
  field_optionally_enclosed_by: "\""
  skip_header: 1
  error_on_column_count_mismatch: false 